### PR TITLE
Initial Implementation

### PR DESCRIPTION
**Pull request by elmigranto**

### CODE REVIEW

**Comment by j3k0** [comment]
> elmigranto requested a review from j3k0 2 hours ago

Do you want me to review the whole boilerplate or anything in particular?

**Comment by elmigranto** [comment]
Oh, nothing yet, but when things are ready, probably should've added you later…

**Comment by j3k0** [comment]
OK, yes add me back when things are ready for review (so I see that in my TODO list and get notified when appropriate)

**Comment by elmigranto** [comment]
This should work if we are okay with everything mentioned in #1.

Will try to figure out bash magic of full tests in the evening :)

**Comment by elmigranto** [comment]
After https://github.com/j3k0/ganomede-events/pull/27 is merged and `ganomede-events@1.2.2` is published without `beta` tag, we can merge this in, it seems? Or do we want anything else here?

**Review by j3k0 — APPROVED** [review]

**Comment by j3k0** [comment]
We can merge this in, it seems complete.

**Pull request closed without merging**
